framework:
    messenger:
        failure_transport: failed

        transports:
            # Transport asynchrone pour les tâches différées
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            # Transport pour les messages échoués
            failed: 'doctrine://default?queue_name=failed'
            # Transport synchrone pour l'envoi direct
            sync: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            # Routage des messages SendEmailMessage vers le transport sync
            Symfony\Component\Mailer\Messenger\SendEmailMessage: sync
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
